### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by Shakhemir** [Shakhemir/deepgit_dz_last#1]
Заполни плиз файл README полезной информацией

**Comment by f0cusStudio** [comment]
а чем именно мне заполнить?

**Comment by Shakhemir** [comment]
напиши задание

**Comment by f0cusStudio** [comment]
ок

**Comment by Shakhemir** [comment]
чуть не забыл. сделай это в новой ветке и затем сделай пулл реквест на мэйн

**Comment by f0cusStudio** [comment]
принял!
